apiVersion: v1
kind: Namespace
metadata:
  name: sekom-mtv-demo
  labels:
    app.kubernetes.io/part-of: sekom-ocp-poc
  annotations:
    openshift.io/display-name: "Sekom OCP POC - MTV ile taşınan VM'ler"
