apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: sekom-ocp-poc
  labels:
    app: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: sekom-ocp-poc
  labels:
    app: php-apache
spec:
  selector:
    app: php-apache
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: php-apache
  namespace: sekom-ocp-poc
  labels:
    app: php-apache
spec:
  to:
    kind: Service
    name: php-apache
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: sekom-ocp-poc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
