apiVersion: v1
kind: LimitRange
metadata:
  name: sekom-ocp-poc-limits
  namespace: sekom-ocp-poc
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 100m
        memory: 128Mi
      min:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: 500m
        memory: 512Mi
    - type: Pod
      max:
        cpu: "1"
        memory: 1Gi
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi
