apiVersion: v1
kind: ResourceQuota
metadata:
  name: sekom-ocp-poc-quota
  namespace: sekom-ocp-poc
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: "10"
    configmaps: "20"
    secrets: "20"
    services: "10"
    persistentvolumeclaims: "5"
