apiVersion: v1
kind: Namespace
metadata:
  name: trt-ocp-poc
  labels:
    app.kubernetes.io/part-of: trt-ocp-poc
    environment: poc
  annotations:
    openshift.io/display-name: "TRT OCP POC"
    openshift.io/description: "TRT OpenShift POC calismalari icin namespace/proje"
