apiVersion: v1
kind: Namespace
metadata:
  name: sekom-ocp-poc-virt-backup
  labels:
    app.kubernetes.io/part-of: sekom-ocp-poc
  annotations:
    openshift.io/display-name: "Sekom OCP POC - VM Backup/Restore"
