# root-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: root-test
  namespace: sekom-psa-scc-test
spec:
  containers:
    - name: test
      image: busybox:1.36
      command: ["id"]
      securityContext:
        runAsUser: 0
