apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: REPLACE_ME_GIT_REPO_URL   # örn. git@bitbucket.org:org/sekom-poc.git ya da https://.../sekom-poc.git
    targetRevision: main
    path: B-UygulamaTeslimi/05-Ci-Cd/app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sekom-ocp-poc-gitops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
