apiVersion: v1
kind: Namespace
metadata:
  name: trt-ocp-poc-win
  labels:
    app.kubernetes.io/part-of: trt-ocp-poc
  annotations:
    openshift.io/display-name: "TRT OCP POC - Windows boot source"
