apiVersion: v1
kind: Secret
metadata:
  name: external-registry-cred
  namespace: sekom-ocp-poc
  labels:
    app: external-registry-demo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "REPLACE_ME_USERNAME",
          "password": "REPLACE_ME_PASSWORD",
          "email": "REPLACE_ME_EMAIL"
        }
      }
    }
