# backup.yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: sekom-oadp-demo-backup
  namespace: openshift-adp
spec:
  includedNamespaces:
    - sekom-oadp-demo
  storageLocation: dpa-odf-1
  ttl: 720h0m0s
