apiVersion: v1
kind: Namespace
metadata:
  name: trt-ocp-poc-virt-backup
  labels:
    app.kubernetes.io/part-of: trt-ocp-poc
  annotations:
    openshift.io/display-name: "TRT OCP POC - VM Backup/Restore"
