# ISO'dan kurulan VM diskinden "golden image" (boot source) üretme
# 1) Kurulu diski klonla  2) DataSource ile boot source olarak yayınla
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: alpine-golden
  namespace: trt-ocp-poc-virt
spec:
  source:
    pvc:
      name: alpine-from-iso-rootdisk
      namespace: trt-ocp-poc-virt
  storage:
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization
    accessModes: [ReadWriteMany]
    volumeMode: Block
    resources:
      requests:
        storage: 5Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: alpine-golden
  namespace: trt-ocp-poc-virt
  labels:
    instancetype.kubevirt.io/default-instancetype: u1.small
    instancetype.kubevirt.io/default-preference: alpine
spec:
  source:
    pvc:
      name: alpine-golden
      namespace: trt-ocp-poc-virt
---
# Golden image'dan yeni VM
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpine-from-golden
  namespace: trt-ocp-poc-virt
spec:
  runStrategy: Always
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.small
  preference:
    kind: VirtualMachineClusterPreference
    name: alpine
  dataVolumeTemplates:
    - metadata:
        name: alpine-from-golden-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: alpine-golden
          namespace: trt-ocp-poc-virt
        storage:
          resources:
            requests:
              storage: 5Gi
  template:
    spec:
      domain:
        devices: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: alpine-from-golden-rootdisk
