apiVersion: snapshot.kubevirt.io/v1beta1
kind: VirtualMachineRestore
metadata:
  name: fedora-restore-1
  namespace: trt-ocp-poc-virt
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: fedora-from-template
  virtualMachineSnapshotName: fedora-snap-1
