# canary-demo.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sekom-canary-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
  namespace: sekom-canary-demo
  labels:
    app: demo-app
    version: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      version: stable
  template:
    metadata:
      labels:
        app: demo-app
        version: stable
    spec:
      containers:
        - name: web
          image: busybox:1.36
          command: ["sh", "-c", "mkdir -p /tmp/www && echo STABLE > /tmp/www/index.html && httpd -f -p 8080 -h /tmp/www"]
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  namespace: sekom-canary-demo
  labels:
    app: demo-app
    version: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      version: canary
  template:
    metadata:
      labels:
        app: demo-app
        version: canary
    spec:
      containers:
        - name: web
          image: busybox:1.36
          command: ["sh", "-c", "mkdir -p /tmp/www && echo CANARY > /tmp/www/index.html && httpd -f -p 8080 -h /tmp/www"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-stable
  namespace: sekom-canary-demo
spec:
  selector:
    app: demo-app
    version: stable
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-canary
  namespace: sekom-canary-demo
spec:
  selector:
    app: demo-app
    version: canary
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-app
  namespace: sekom-canary-demo
spec:
  to:
    kind: Service
    name: app-stable
    weight: 90              # <-- ana trafiğin %90'ı stable'a
  alternateBackends:
    - kind: Service
      name: app-canary
      weight: 10             # <-- %10'u canary'ye
  port:
    targetPort: 8080
