apiVersion: v1
kind: Namespace
metadata:
  name: sekom-ocp-poc-virt
  labels:
    app.kubernetes.io/part-of: sekom-ocp-poc
  annotations:
    openshift.io/display-name: "Sekom OCP POC - Virtualization"
    openshift.io/description: "Sekom OpenShift Virtualization POC calismalari icin namespace/proje"
